version: "2.4"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  maildev:
    restart: always
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "${MAIL_PORT}:25"
